### PR TITLE
fix anythingType making nil specs

### LINKED ISSUE #22: AnythingType produces a nil spec
when we use `flanders.utils/replace-either-with-any` what happens is that it replaces all conditionals/either with AnythingType as expected.
with Schema `AnythingType` translates to `Any`, with spec it should use `any?`.
However the spec part also has gen support, the part that treats AnythingType looks like this:

```clojure
 AnythingType
 (->spec' [{:keys [gen spec]} _ _]
   (with-gen
     (or spec
         any?)
     gen))
```

but the others look like that:

```clojure
InstType
 (->spec' [{:keys [spec] :as node} _ _]
   (with-gen node
     (or spec
         inst?)))
```

so AnythingType returns gen which takes its data from some destructuring from `node`like this:

```clojure
(defn with-gen
 "Used like clojure.spec/with-gen, except that it takes a node (that
 may have :_gen set) and a spec.  If set, :_gen must be a function
 of zero args that returns a generator."
 [{gen :_gen} spec]
 (if gen
   (s/with-gen spec gen)
   spec))
```
here the argument passed to with-gen is gen and not spec and that produces `nil` in the end,
which finally outputs a NPE when used with cs/valid?

### PR DESCRIPTION
**Pull request by gbuisson**
closes #22

This change aligns `AnythingType `with the other types, and stops spec from outputting exceptions while validating entities where `conditional`s are replaced with `any`.

### CODE REVIEW

File: src/flanders/spec.clj [hunk 1]
```diff
@@ -110,11 +110,9 @@
   ;; Leaves
 
   AnythingType
-  (->spec' [{:keys [gen spec]} _ _]
-    (with-gen
-      (or spec
-          any?)
-      gen))
+  (->spec' [{:keys [gen spec] :as node} _ _]
```
Comment (msprunck) [inline src/flanders/spec.clj]: You could remove `gen` from the destructuring.

**Comment by hshahman** [comment]
No QA required.
